import { Root } from "@/Components/Root";
import "./globals.css";
import type { Metadata } from "next";
import { Heebo } from "next/font/google";

const inter = Heebo({ subsets: ["hebrew"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={inter.style}>
        <Root>{children}</Root>
      </body>
    </html>
  );
}
